#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Stop the service if it's running
        if systemctl is-active --quiet rustdesk-hbbr; then
            systemctl stop rustdesk-hbbr || true
        fi
        ;;
esac

#DEBHELPER#

exit 0